#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const assert = require('assert');

const root = path.resolve(__dirname, '..');
const jsPath = path.join(root, 'admin', 'chatbot-customizer.js');
const cssPath = path.join(root, 'admin', 'chatbot-customizer.css');

assert.ok(fs.existsSync(jsPath), 'admin/chatbot-customizer.js missing');
assert.ok(fs.existsSync(cssPath), 'admin/chatbot-customizer.css missing');

const js = fs.readFileSync(jsPath, 'utf8');
const css = fs.readFileSync(cssPath, 'utf8');

[
  'window.EasiioChatbotCustomizer',
  'data-easiio-chatbot-customizer',
  'data-site-id',
  'data-api-base',
  '/api/chat/form-config',
  '/api/email-agent/config',
  '/api/rag/content',
  '/api/rag/content/delete',
  '/api/rag/debug',
  '/api/rag/answer-log',
  '/api/rag/feedback',
  '/api/rag/eval',
  '/api/rag/sources',
  '/api/rag/sync-sources',
  '/api/rag/sync-preview',
  '/api/rag/review',
  '/api/rag/rollback',
  '/api/rag/refresh-schedule',
  '/api/rag/refresh-due',
  '/api/rag/run-scheduled-refresh',
  '/api/rag/notifications',
  '/api/rag/notifications/read',
  '/api/rag/source-items',
  '/api/rag/wordpress/pull',
  '/api/rag/upload/extract',
  'RAG source sync',
  'RAG schedule + notifications',
  'data-rag-sync-source',
  'data-sync-rag-sources',
  'data-save-rag-schedule',
  'data-run-rag-scheduled-refresh',
  'data-load-rag-notifications',
  'renderRagNotifications',
  'saveRagSchedule',
  'runScheduledRefresh',
  'loadRagDue',
  'loadRagSources',
  'renderRagSources',
  'syncRagSources',
  'saveExternalSourceItems',
  'data-rag-source-import',
  'RAG review queue',
  'data-load-rag-review',
  'data-preview-rag-sync',
  'data-rollback-rag-sync',
  'renderRagReview',
  'loadRagReview',
  'previewRagSync',
  'rollbackRagSync',
  'deleted_upstream',
  'WordPress import',
  'Uploaded document import',
  'data-rag-wordpress-pull',
  'pullWordPressSource',
  'data-rag-upload-extract',
  'extractUploadDocument',
  'WordPress REST pull',
  'Document extraction',
  'loadRagDebug',
  'renderRagDebug',
  'sendRagFeedback',
  'loadFormConfig',
  'saveFormConfig',
  'loadNotificationEmailConfig',
  'saveNotificationEmailConfig',
  'notificationEmailPayloadFromForm',
  'addFormField',
  'removeFormField',
  'loadKnowledgeBase',
  'saveKnowledgeItem',
  'deleteKnowledgeItem',
  'renderPreview',
  'textarea',
  'message',
  'phone',
  'Notification email settings',
  'data-notification-email-editor',
  'data-notification-email-recipients',
  'send_owner_notification',
  'owner_recipients',
  'send_welcome_email',
  'owner_subject',
  'owner_body',
  'Welcome email to visitor',
  'Owner notification email',
  'Voice playback settings',
  'DEFAULT_WIDGET_CONFIG',
  'normalizeWidgetConfig',
  'data-widget-config-editor',
  'data-widget-voice-enabled',
  'data-widget-voice-preview',
  'widgetConfigPayloadFromForm',
  'saveWidgetConfig',
  'loadWidgetConfig',
  'renderWidgetVoicePreview',
  'voice_enabled',
  'voice_label',
  'voice_autoplay',
  'voice_format',
  'voice_input_enabled',
  'voice_input_label',
  'voice_input_language',
  'data-widget-voice-input-enabled',
  'Voice input settings',
  'widget_config',
  'Voice call settings',
  'voice_call_enabled',
  'voice_call_label',
  'voice_call_api_base',
  'voice_call_consent_text',
  'data-widget-voice-call-enabled',
  'data-widget-voice-call-api-base',
  'chatbot-widget-voice-call-settings',
  'data-voice-call-enabled',
  'data-voice-call-api-base'
].forEach(token => assert.ok(js.includes(token), `${token} missing from customizer JS`));

assert.ok(/fields\s*:\s*\[[\s\S]*name:\s*['"]name['"][\s\S]*name:\s*['"]email['"][\s\S]*name:\s*['"]company['"][\s\S]*name:\s*['"]message['"]/.test(js), 'default fields should include name/email/company/message');
assert.ok(!/name:\s*['"]phone['"]/.test(js), 'phone should not be a default lead form field');
assert.ok(/credentials\s*:\s*['"]same-origin['"]/.test(js), 'admin module should use same-origin credentials by default');

[
  '.easiio-chatbot-customizer',
  '.chatbot-customizer-grid',
  '.chatbot-field-row',
  '.chatbot-kb-list',
  '.chatbot-preview-form',
  '.chatbot-notification-card',
  '.chatbot-notification-grid',
  '.chatbot-notification-preview',
  '.chatbot-widget-config-card',
  '.chatbot-widget-config-grid',
  '.chatbot-widget-voice-call-settings',
  '.chatbot-widget-voice-preview',
  '.chatbot-widget-embed-snippet',
  '.chatbot-rag-debug-card',
  '.chatbot-rag-sync-card',
  '.chatbot-rag-source-list',
  '.chatbot-rag-source-row',
  '.chatbot-rag-sync-options',
  '.chatbot-rag-sync-results',
  '.chatbot-rag-external-grid',
  '.chatbot-rag-source-import',
  '.chatbot-rag-review-panel',
  '.chatbot-rag-review-row',
  '.chatbot-rag-review-status',
  '.chatbot-rag-diff-preview',
  '.chatbot-rag-schedule-card',
  '.chatbot-rag-notification-list',
  '.chatbot-rag-notification-row',
  '.chatbot-rag-pipeline-form',
  '.chatbot-rag-debug-results',
  '.chatbot-rag-feedback-row',
  '.chatbot-rag-eval-results',
  '.chatbot-status',
  'box-sizing: border-box',
  'repeat(auto-fit, minmax(140px, 1fr))',
  '@media (max-width: 1200px)',
  'overflow: hidden'
].forEach(token => assert.ok(css.includes(token), `${token} missing from customizer CSS`));

console.log('PASS chatbot customizer admin module static checks');
